# This file can be used to install module dependencies for unit testing
# See https://github.com/puppetlabs/puppetlabs_spec_helper#using-fixtures for details
---
fixtures:
  forge_modules:
    archive:
      repo: puppet/archive
      ref: 7.0.0
    stdlib:
      repo: puppetlabs/stdlib
      ref: 9.3.0
    bsys:
      repo: aursu/bsys
      ref: 0.2.0
